GroInventory/Models/Department.cs
using System;
using System.Collections.Generic;

namespace GroInventory.Models
{
    public class Department
    {
        public string DeptName { get; set; }
        public int DeptID { get; set; }
        public static IEnumerable<Department> DeptList { get; set; }
    }
}

GroInventory/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GroInventory.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GroInventory.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDeptRepo repo;

        public DepartmentController(IDeptRepo repo)
        {
            this.repo = repo;
        }

        // GET: /<controller>/
        public IActionResult DeleteDept(Department dept)
        {
            repo.DeleteDept(dept);

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            Department.DeptList = repo.GetDepartments();

            return View(Department.DeptList);
        }

        public IActionResult InsertDepartment()
        {
            //var prod = repo.AssignDepartmentsList();
            //repo.AssignLikeCodeList(prod);

            //return View(prod);

            var dept = new Department();

            return View(dept);
        }

        public IActionResult InsertDeptToDatabase(Department deptToInsert)
        {
            repo.InsertDept(deptToInsert);

            return RedirectToAction("Index");
        }

        public IActionResult UpdateDepartment(int id)
        {
            var dept = repo.GetDept(id);

            if (dept == null)
            {
                return View("DepartmentNotFound");
            }

            return View(dept);
        }

        public IActionResult UpdateDeptToDatabase(Department dept)
        {
            repo.UpdateDept(dept);

            return RedirectToAction("ViewDepartment", new { id = dept.DeptID });
        }

        public IActionResult ViewDepartment(int id)
        {
            var dept = repo.GetDept(id);

            return View(dept);
        }
    }
}

GroInventory/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GroInventory.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GroInventory.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository repo;

        public ProductController(IProductRepository repo)
        {
            this.repo = repo;
        }

        // GET: /<controller>/
        public IActionResult DeleteProduct(Product product)
        {
            repo.DeleteProduct(product);

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            var products = repo.GetAllProducts();

            Department.DeptList = repo.GetDepartments();
            LikeCode.LikeCodeList = repo.GetLikeCodes();

            return View(products);
        }

        public IActionResult InsertProduct()
        {
            var prod = repo.AssignDepartmentsList();
            repo.AssignLikeCodeList(prod);

            return View(prod);
        }

        public IActionResult InsertProductToDatabase(Product productToInsert)
        {
            //add code here to check if UPC/PLU already taken; if so, redirect back to InsertProduct.cshtml

            repo.InsertProduct(productToInsert);

            return RedirectToAction("Index");
        }

        //Search Bar
        public IActionResult Search(string searchString)
        {
            var search = repo.SearchProduct(searchString);

            return View(search);
        }

        public IActionResult UpdateProduct(int id)
        {
            Product prod = repo.GetProduct(id);

            if (prod == null)
            {
                return View("ProductNotFound");
            }

            return View(prod);
        }

        public IActionResult UpdateProductToDatabase(Product product)
        {
            repo.UpdateProduct(product);

            return RedirectToAction("ViewProduct", new { id = product.UPCPLU });
        }

        public IActionResult ViewProduct(int id)
        {
            var product = repo.GetProduct(id);

            Department.DeptList = repo.GetDepartments();
            LikeCode.LikeCodeList = repo.GetLikeCodes();

            return View(product);
        }
    }
}

GroInventory/Views/Department/Index.cshtml
@model IEnumerable<Department>

<h2>Departments</h2>


<table class="container-fluid">
    @*<tr>
        <td>
            @using (Html.BeginForm("Search", "Product", FormMethod.Get))
            {
                <p>
                    Search by Name or UPC:<br>
                    @Html.TextBox("searchString")
                    <input type="submit" value="Search" />
                </p>
            }
        </td>
    </tr>*@
    <tr>
        <td>
            <button type="button" class="btn btn-primary">
                <a class="text-light" href="/Department/InsertDepartment/">Create a New Department</a>
            </button>
        </td>
    </tr>
</table>


<br>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr class="text-center">
            <th>Department ID</th>
            <th>Department Name</th>
        </tr>
    </thead>

    @foreach (var dept in Model)
    {
        <tr class="text-center">
            <td><a href=/Department/ViewDepartment/@dept.DeptID>@dept.DeptID</a></td>
            <td><a href=/Department/ViewDepartment/@dept.DeptID>@dept.DeptName</a></td>
        </tr>
    }
</table>

GroInventory/Views/Department/InsertDepartment.cshtml
@model Department
<h2>Create a New Department</h2>

<p class="text-danger">
    required *
</p>
<br />

@using (Html.BeginForm("InsertDeptToDatabase", "Department", "Post"))
{
    @*<label asp-for="DeptID" class="control-label">UPC/PLU</label><span style="color:red">*</span>
    <input type="text" name="UPCPLU" class="form-control" value="" />
    <br>*@

    <label asp-for="DeptName" class="control-label">Department Name</label><span style="color:red">*</span>
    <input type="text" name="DeptName" class="form-control" value="" />
    <br>

    @*<label asp-for="WarehouseCode" class="control-label">Warehouse Code</label>
    <input type="text" name="WarehouseCode" class="form-control" value="" />
    <br>

    <label asp-for="Price" class="control-label">Price</label><span style="color:red">*</span>
    <input type="number" step="0.01" name="Price" class="form-control" />

    <label asp-for="PerPound" class="control-label">Per Pound?</label>
    <input type="checkbox" name="PerPound" id="PerPound" value="true" />
    <br>
    <br>

    <label asp-for="SalePrice" class="control-label">Sale Price</label>
    <input type="number" step="0.01" name="SalePrice" class="form-control" value="@Model.SalePrice" />
    <br>

    <div class="form-group">
        <label for="">On Sale?</label>
        <select class="form-control" name="OnSale" value="">
            <option value="false" selected>No</option>
            <option value="true">Yes</option>
        </select>
    </div>
    <br>

    <label asp-for="UnitsPerCase" class="control-label">Units/Case</label>
    <input type="text" name="UnitsPerCase" class="form-control" value="" />
    <br>

    <label asp-for="CaseCost" class="control-label">Case Cost</label>
    <input type="text" name="CaseCost" class="form-control" value="" />
    <br>

    <div class="form-group">
        <label asp-for="DeptID">Select a Department</label><span style="color:red">*</span>
        <select class="form-control" name="DeptID" value="">
            @foreach (var dept in Department.DeptList)
            {
                //if gets rid of 0 No Dept option
                @if (dept.DeptID > 0)
                {
                    <option value="@dept.DeptID"> @dept.DeptID @dept.DeptName</option>
                }
            }
        </select>
    </div>
    <br>

    <label asp-for="CurrentInventory" class="control-label">Current Inventory</label>
    <input type="text" name="CurrentInventory" class="form-control" value="" />
    <br>*@

    <input type="submit" value="Create Department" class="btn btn-primary" />

    <button type="button" class="btn btn-warning">
        <a class="text-light" href="/Department/Index/">Cancel</a>
    </button>
}

GroInventory/Views/Department/UpdateDepartment.cshtml
@model Department
<h2>Update @Model.DeptName</h2>

@using (Html.BeginForm("UpdateDeptToDatabase", "Department", "Post"))
{
    <input asp-for="DeptID" type="hidden" value="@Model.DeptID" />

    <label asp-for="DeptName" class="control-label">Department Name</label>

    <input type="text" name="DeptName" class="form-control" value="@Model.DeptName" />
    @*<br>

    <label asp-for="WarehouseCode" class="control-label">Warehouse Code</label>
    <input type="text" name="WarehouseCode" class="form-control" value="@Model.WarehouseCode" />
    <br>

    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" step="0.01" name="Price" class="form-control" value="@Model.Price" />

    @if (Model.PerPound)
    {
        <label asp-for="PerPound" class="control-label">Per Pound?</label>
        <input type="checkbox" name="PerPound" id="PerPound" value="true" checked />
    }
    else
    {
        <label asp-for="PerPound" class="control-label">Per Pound?</label>
        <input type="checkbox" name="PerPound" id="PerPound" value="true" />
    }

    <br>
    <br>

    <label asp-for="SalePrice" class="control-label">Sale Price</label>
    <input type="number" step="0.01" name="SalePrice" class="form-control" value="@Model.SalePrice" />
    <br>

    <div class="form-group">
        <label for="">On Sale?</label>
        <select class="form-control" name="OnSale" value="@Model.OnSale">
            @if (Model.OnSale)
            {
                <option value="true" selected>Yes</option>
                <option value="false">No</option>
            }
            else
            {
                <option value="true">Yes</option>
                <option value="false" selected>No</option>
            }
        </select>
    </div>
    <br>

    <label asp-for="UnitsPerCase" class="control-label">Units/Case</label>
    <input type="text" name="UnitsPerCase" class="form-control" value="@Model.UnitsPerCase" />
    <br>

    <label asp-for="CaseCost" class="control-label">Case Cost</label>
    <input type="text" name="CaseCost" class="form-control" value="@Model.CaseCost" />
    <br>

    <div class="form-group">
        <label asp-for="DeptID">Select a Department</label><span style="color:red">*</span>
        <select class="form-control" name="DeptID" value="@Model.DeptName">
            @foreach (var dept in Department.DeptList)
            {
                //if gets rid of 0 No Dept option
                @if (dept.DeptID > 0)
                {
                    @if (Model.DeptID == dept.DeptID) //Makes current dept selected
                    {
                        <option value="@dept.DeptID" selected> @dept.DeptID @dept.DeptName</option>
                    }
                    else
                    {
                        <option value="@dept.DeptID"> @dept.DeptID @dept.DeptName</option>
                    }

                }
            }
        </select>
    </div>
    <br>

    <label asp-for="CurrentInventory" class="control-label">Current Inventory</label>
    <input type="text" name="CurrentInventory" class="form-control" value="@Model.CurrentInventory" />
    <br>*@

    @*<label asp-for="LikeCodeID" class="control-label">Like Code</label>
        <input type="text" name="LikeCodeID" class="form-control" value="@Model.LikeCodeID" />
        <br>*@

    <br>

    <input type="submit" value="Update Department" class="btn btn-primary" />

    <button type="button" class="btn btn-warning">
        <a class="text-light" href="/Department/ViewDepartment/@Model.DeptID">Cancel</a>
    </button>
}

GroInventory/Views/Department/ViewDepartment.cshtml
@model Department

<h3>@Model.DeptName Information</h3>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr class="text-center">
            <th>Department ID</th>
            <th>Department Name</th>
        </tr>
    </thead>
    <tr class="text-center">
        <td>@Model.DeptID</td>
        <td>@Model.DeptName</td>
    </tr>
</table>

<br>

<div>
    <button type="button" class="btn btn-primary">
        <a class="text-light" href="/Department/UpdateDepartment/@Model.DeptID">Update this Department</a>
    </button>
</div>

<br>

<div style="display: block">
    @using (Html.BeginForm("DeleteDept", "Department", "Post"))
    {
        <input type="hidden" asp-for="DeptID" value="@Model.DeptID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this Department" class="btn btn-danger" />
    }
</div>